### ISSUE TITLE
As a developer, I want to know how I can sort data in Python, so that I organise incoming json files.

### ISSUE THREAD

**Issue by TylerRijk** [Team-Programmeer-Profeten/ShareDiMobiHub-backend#1]
# Description

As a developer tasked with processing and analyzing data from JSON files from a certain API, it's crucial to have the capability to sort this data efficiently in Python. 

# Definition of Done

- [ ] You understand the basics of sorting in Python
- [ ] You know how to make a custom sorting algorithm in Python
- [ ] You can explain to your peers how to sort large JSON files in Python

# Tasks

- [ ] #2
