### ISSUE TITLE
As a developer, I want to request the data based on the given filters, so that we can generate a report.

### ISSUE THREAD

**Issue by TylerRijk** [Team-Programmeer-Profeten/ShareDiMobiHub-backend#12]
# Description

We want to request certain data from the given Mock API's based from the filters from our frontend.

# Definition of Ready

- [ ] Given Mock API's are reachable
- [ ] #9 

# Definition of Done

- [ ] The data based on the given filters can be returned

# Tasks

- [ ] Make function to request data from Mock API
- [ ] Add error handling
