### ISSUE TITLE
As a developer, I want setup a Docker container, so that I can deploy the backend in a reusable environment.

### ISSUE THREAD

**Issue by TylerRijk** [Team-Programmeer-Profeten/ShareDiMobiHub-backend#15]
# Description

It is a requirement to deploy the backend in a Docker container.

# Definition of Ready

- [ ] #7
- [ ] Docker is installed

# Definition of Done

- [ ] The container is running and reachable

# Tasks

- [ ] Setup the Docker container
