### ISSUE TITLE
As a municipality employee, I want to have an infographic on the first-page of my report, so that I have an overview of my municipality.

### ISSUE THREAD

**Issue by TylerRijk** [Team-Programmeer-Profeten/ShareDiMobiHub-backend#41]
# Description

On the generated report, there has to be an infographic about the municipality of the employee on the first page.

# Definition of Ready

- [ ] All data is available that needs to be on the first page
- [ ] There is a good understanding of all the data can be displayed on the first page

# Definition of Done

- [ ] The data from the requested municipality is shown on the infographic
- [ ] The infographic can be send back to the frontend
- [ ] Easy to understand

# Tasks

- [ ] Make a design / mockup of the infographic
- [ ] Make a template pdf
- [ ] Add requested data on the infographic
