### ISSUE TITLE
As a developer, I want to learn how to make requests to an API using Python, so I can use this knowledge in the project.

### ISSUE THREAD

**Issue by TylerRijk** [Team-Programmeer-Profeten/ShareDiMobiHub-backend#5]
# Description

We want to make requests to the given API, to gather the data that we need but how can we do this in the best way in Python.

# Definition of Done

- [ ] Clear understanding of how to make HTTP requests using Python.
- [ ] Clear understanding of HTTP error handling.

# Tasks

- [ ] Learn how to make HTTP requests using Python
