### ISSUE TITLE
As a municipality employee, I want to see multiple graphs from my chosen subjects, so that I have a good overview.

### ISSUE THREAD

**Issue by TylerRijk** [Team-Programmeer-Profeten/ShareDiMobiHub-backend#56]
# Description

An employee selected a few subjects in the front-end and all the subjects that are chosen have to be added to the pdf. For every subject we want to see 2 different graphs over the chosen subject.

# Definition of Ready

- [ ] Front-end can send requests to the server with the chosen details
- [ ] The infographic is done, so you can see which topics are selected
- [ ] Know how to make graphs and add them to the pdf

# Definition of Done

- [ ] Every subject has a dedicated page in the pdf with a minimal of 2 graphs per subject.

# Tasks

## Number of Vehicles
- [ ] Graph of the number of vehicles in the municipality, total and per service provider with timesteps for the selected period

## Distance Covered
- [ ] A vertical bar chart of the distance covered with time steps of half a year
- [ ] A vertical bar chart of the distance covered with time steps of months

## Rentals
- [ ] Graph of the rentals in the municipality and the selected neighbourhoods for the selected period
- [ ] Bar chart of the rentals in the selected neighbourhoods per day of the week

## Parking Time
- [ ] A horizontal bar chart of the average parking time by vehicle type [Vehicle Type]
- [ ] A horizontal bar chart of the average parking time by service provider [Vehicle Provider]

## Hub
- [ ] Average occupation per hub
- [ ] Vertical multi-bar chart with parking time per hub
