### ISSUE TITLE
As a developer, I want to learn how I can setup a Docker container, so that I can implement this in the project.

### ISSUE THREAD

**Issue by TylerRijk** [Team-Programmeer-Profeten/ShareDiMobiHub-backend#7]
# Description

We need to setup a Docker container with our backend script. Learn how this works.

# Definition of Done

- [ ] Clear understanding of how a Docker container works.
- [ ] Know how to setup a container.

# Tasks

- [ ] Learn how to setup a Docker container
