### ISSUE TITLE
As a developer, I want to make a REST server Python, so that my frontend can send requests.

### ISSUE THREAD

**Issue by TylerRijk** [Team-Programmeer-Profeten/ShareDiMobiHub-backend#9]
# Description

We want to receive requests from the Frontend to our Backend. In this request we can find the filters of the report.

# Definition of Ready

- [ ] Know how to make a REST server in Python
- [ ] Filters are known from the frontend

# Definition of Done

- [ ] We can receive requests on our endpoints
- [ ] Our code is created RESTful
- [ ] We can read the filters from the json body from the request
- [ ] We can send mock data back

# Tasks

- [ ] Setup a default Python project structure
- [ ] Make a REST controller with a RESTful endpoint
